/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    "min-h-screen",
    "flex-1",
    "min-h-0",
    "flex",
    "flex-col",
    "shrink-0",
    "w-full",
    "max-w-2xl",
    "max-w-4xl",
    "max-w-5xl",
    "scroll-smooth",
    "bg-slate-50",
    "text-slate-900",
    "antialiased",
    "bg-bagana-primary",
    "bg-bagana-secondary",
    "text-bagana-primary",
    "text-bagana-dark",
    "text-bagana-accent",
    "bg-bagana-muted",
    "bg-bagana-muted/50",
    "border-bagana-primary",
    "hover:bg-bagana-secondary",
    "focus:ring-bagana-primary/20",
    "focus:border-bagana-primary",
    "focus-within:ring-2",
    "focus-within:ring-bagana-primary/20",
    "bg-white/80",
    "backdrop-blur",
    "border-slate-200",
    "border-slate-300",
    "text-slate-500",
    "text-slate-600",
    "text-slate-700",
    "text-slate-800",
    "bg-white",
    "shadow-sm",
    "hover:shadow-md",
    "rounded-xl",
    "rounded-lg",
    "rounded-md",
    "transition-colors",
    "transition-shadow",
    "bg-emerald-100",
    "text-emerald-800",
    "bg-amber-100",
    "text-amber-800",
    "bg-slate-100",
    "text-slate-400",
    "line-clamp-3",
    "touch-target",
    "border-b-2",
    "pb-0.5",
    "hover:text-slate-700",
    "hover:bg-slate-100",
    "hidden",
    "lg:flex",
    "lg:hidden",
    "relative",
    "fixed",
    "inset-0",
    "z-40",
    "z-50",
    "gap-4",
    "xl:gap-6",
    "items-center",
    "flex-wrap",
    "placeholder:text-slate-400",
    "disabled:opacity-50",
    "disabled:cursor-not-allowed",
    "rounded-2xl",
    "overflow-y-auto",
    "space-y-6",
    "grid",
    "grid-cols-1",
    "sm:grid-cols-2",
    "lg:grid-cols-4",
    "gap-4",
    "sm:gap-5",
    "text-2xl",
    "sm:text-3xl",
    "text-base",
    "sm:text-lg",
    "inline-flex",
    "justify-center",
    "px-4",
    "sm:px-6",
    "py-3",
    "py-12",
    "sm:py-16",
    "mb-4",
    "mb-8",
    "mb-10",
    "sm:mb-12",
  ],
  theme: {
    extend: {
      colors: {
        bagana: {
          primary: "#0f766e",
          secondary: "#0d9488",
          accent: "#14b8a6",
          muted: "#99f6e4",
          dark: "#134e4a",
        },
      },
    },
  },
  plugins: [],
};
